apiVersion: v1
kind: PersistentVolume
metadata:
  name: os-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jking/GolandProjects/os-online/vol"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: os-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi



